### ISSUE TITLE
Does not support intelliJ 2020.1?

### ISSUE THREAD

**Issue by yakkle** [Hinaser/gfm-advanced#3]
I want to try this on stable release.
Could you support to IntelliJ 2020.1?

**Comment by Hinaser** [comment]
Hi

This plugin uses JCEF (Java Chromium Embbeded Framework) which is enabled by default 2020.2 onwards.
I confirmed that even in 2020.1, JCEF is available when user manually activate it as described in https://jetbrains.org/intellij/sdk/docs/reference_guide/jcef.html .

Technically speaking, this plugin should run without error in 2020.1 when JCEF is activated.
The problem is plugin installation I think.

I'll investigate how to install and run the plugin in 2020.1.

**Comment by yakkle** [comment]
IntelliJ 2020.2 released. 😄

**Comment by Hinaser** [comment]
So you don't need 2020.1 support anymore?

**Comment by yakkle** [comment]
@Hinaser 
Yes. I have updated `IntelliJ 2020.2` and installed `gfmA`.

However, I have tried to activate JCEF in `intelliJ 2020.1` following [instruction](https://jetbrains.org/intellij/sdk/docs/reference_guide/jcef.html) and I think I can use it as long as I can install plugin.
If possible, wouldn't it be better to support the previous version?

**Comment by Hinaser** [comment]
@yakkle 
Thanks for reporting!

I think your report which suggests gfmA works in 2020.1 when JCEF is activated is totally sufficient.
If I marked this plugin as compatible to 2020.1, maybe some users who don't know it requires JCEF activation feel so frustrated.

So I leave gfmA compatibility setting as it is.

If anything you would like to suggest, I am listening.
